### ISSUE TITLE
incorrect links

### ISSUE THREAD

**Issue by BBBalls** [winterdharma/DharmaPearls#6]
On [The Medium Discourses](https://canon.dharmapearls.net/01_agama/madhyama/)  MA9 and MA10 are linked to MA8.

The title of MA9 is incorrect in the source file. It is currently `<title>The Medium Discourses | Chapter 1: Sevens | 10. Ending the Contaminants</title>`

Thanks for the translating the Agamas, and making them freely available.

**Comment by winterdharma** [comment]
Thanks for taking the time to point out these corrections!
